RED="\e[1;31m"
YELLOW="\e[1;33m"
RESET="\e[1;32m"

startline="0"
fulloutput=(
"                                %s"
"            ${RED} .-.'  '.-. ${RESET}          %s"
"         ${RED} .-(   \  /   )-. ${RESET}      %s"
"        ${RED} /   '..${YELLOW}oOOo..${RED}'   \ ${RESET}     %s"
" ,      ${RED} \.--.${YELLOW}oOOOOOOo.${RED}--./ ${RESET}    %s"
" |\  ,  ${RED} (   :${YELLOW}oOOOOOOo: ${RED}  ) ${RESET}    %s"
"_\.\/|  ${RED} /'--'${YELLOW}oOOOOOOo'${RED}--'\ ${RESET}    %s"
"'-.. ;/|${RED} \   .''${YELLOW}oOOo''${RED}.   / ${RESET}    %s"
".--''. :/|${RED}'-(   /  \   )-' ${RESET}     %s"
" '--. '. / //'-'.__.'-;  ${RESET}       %s"
"   ''-,_';//      ,  /|         %s"
"        '((       |\/./_        %s"
"          \\\\  . |\; ..-'        %s"
"           \\\\ |\: .''--.        %s"
"            \\\\, .' .--'         %s"
"             ))'_,-''           %s"
"       jgs  //-'                %s"
"           //                   %s"
"          //                    %s"
"         |/")