# This is a Makefile for producing a latex pdf.
# Repo: https://github.com/fiedl/dot-zsh
#
# Just type `make` to run it.
#
# I've migrated to rake (https://github.com/ruby/rake) to replace `make`.
# Thus, have a look at the `Rakefile` rather than the `Makefile`.

run:
	rake
